CREATE TABLE ROLE(
    NAME VARCHAR(30) NOT NULL PRIMARY KEY,
    CAN_VIEW_CHAPTERS BOOLEAN NOT NULL DEFAULT false,
    CAN_ADD_BOOKS BOOLEAN NOT NULL DEFAULT false,
    CAN_ADD_CHAPTERS BOOLEAN NOT NULL DEFAULT false,
    CAN_ADD_GENRES BOOLEAN NOT NULL DEFAULT false,
    CAN_ADD_BOOK_FORMATS BOOLEAN NOT NULL DEFAULT false,
    CAN_ADD_RATINGS BOOLEAN NOT NULL DEFAULT false,
    CAN_CHANGE_RATINGS BOOLEAN NOT NULL DEFAULT false
);