CREATE TABLE AUTHOR (
    LOGIN VARCHAR (40) NOT NULL PRIMARY KEY,
    NAME VARCHAR (100) NOT NULL,
    PASSWORD VARBINARY NOT NULL,
    ROLE_NAME VARCHAR(30) NOT NULL,
    CONSTRAINT FK_USER_ROLE FOREIGN KEY (ROLE_NAME) REFERENCES ROLE(NAME)
                ON DELETE CASCADE ON UPDATE CASCADE,
    REGISTRATION_DATE DATETIME NOT NULL,
    BIRTH_DATE DATE NOT NULL
);