CREATE TABLE CHAPTER (
    BOOK_ID INTEGER NOT NULL,
    CONSTRAINT FK_CHAPTER_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID)
            ON DELETE CASCADE ON UPDATE CASCADE,
    NUMBER INTEGER NOT NULL,
    CREATION_DATE DATETIME NOT NULL,
    NAME   VARCHAR (50),
    TEXT   CHARACTER LARGE OBJECT NOT NULL,
    IS_VISIBLE BOOLEAN NOT NULL DEFAULT false,
    PRIMARY KEY (
        BOOK_ID,
        NUMBER
    )
);
