INSERT INTO ROLE(NAME, CAN_VIEW_CHAPTERS, CAN_ADD_BOOKS, CAN_ADD_CHAPTERS, CAN_ADD_GENRES, CAN_ADD_BOOK_FORMATS, CAN_ADD_RATINGS, CAN_CHANGE_RATINGS)
    VALUES ('ADMIN', true, true, true, true, true, true,true);
INSERT INTO ROLE(NAME, CAN_VIEW_CHAPTERS, CAN_ADD_BOOKS, CAN_ADD_CHAPTERS)
    VALUES ('USER', true, true, true);
